export {
  type AdapterId,
  type AgentAction,
  type AgentAdapter,
  type AgentDecision,
  adapterIdSchema,
  agentActionSchema,
  agentAdapterSchema,
  agentDecisionSchema,
  type DecisionReasonCode,
  type DeploymentTrust,
  decisionReasonCodeSchema,
  deploymentTrustSchema,
  type ShellDialect,
  serializeAgentDecision,
  shellDialectSchema,
} from "./actions/domain.js";
export {
  type CommandQualification,
  commandQualificationSchema,
  type QualificationReason,
  type QualifiedPackage,
  qualificationReasonSchema,
  qualifyCommand,
} from "./actions/qualify-command.js";
export {
  type ApprovalApplication,
  type ApprovalFile,
  type ApprovalRecord,
  type ApprovalTimeSummary,
  applyApprovals,
  approvalFileSchema,
  approvalRecordSchema,
  summarizeApprovalTimes,
} from "./approvals/index.js";
export {
  type CacheProbeState,
  type CacheProvider,
  type CacheReadResult,
  cacheKeyDigest,
  defaultCacheRoot,
  MetadataCache,
  type MetadataCacheOptions,
} from "./cache/metadata-cache.js";
export {
  type ApprovalValidationReport,
  approvalValidationReportSchema,
  type ClaudeLocalSettingsIgnored,
  type ClaudeProjectHookBlocker,
  type ClaudeProjectHookLifecycleReport,
  type ClaudeProjectHookOwnership,
  type ClaudeProjectHookReadiness,
  type ClaudeProjectHookStatusReport,
  type ClaudeSettingsState,
  type ClaudeSharedDisableAllHooks,
  type ClaudeSharedPreToolUse,
  type CliErrorReport,
  type CodexProjectHookBlocker,
  type CodexProjectHookLifecycleReport,
  type CodexProjectHookOwnership,
  type CodexProjectHookReadiness,
  type CodexProjectHookStatusReport,
  claudeLocalSettingsIgnoredSchema,
  claudeProjectHookBlockerSchema,
  claudeProjectHookLifecycleReportSchema,
  claudeProjectHookOwnershipSchema,
  claudeProjectHookReadinessSchema,
  claudeProjectHookStatusReportSchema,
  claudeSettingsStateSchema,
  claudeSharedDisableAllHooksSchema,
  claudeSharedPreToolUseSchema,
  cliErrorCodeSchema,
  cliErrorReportSchema,
  codexProjectHookBlockerSchema,
  codexProjectHookLifecycleReportSchema,
  codexProjectHookOwnershipSchema,
  codexProjectHookReadinessSchema,
  codexProjectHookStatusReportSchema,
  type DiffReport,
  type DoctorReport,
  diffReportSchema,
  directDependencySchema,
  doctorReportSchema,
  type InitIntegration,
  type InitReport,
  type InitTarget,
  type InventoryReport,
  initIntegrationSchema,
  initReportSchema,
  initTargetSchema,
  inventoryReportSchema,
  type PolicyValidationReport,
  parseDoctorNodeMajor,
  policyValidationReportSchema,
  type ScanReport,
  scanReportSchema,
} from "./cli-contract.js";
export {
  type AgentHawkConfig,
  agentHawkConfigSchema,
  type PolicyAction,
  policyActionSchema,
} from "./config.js";
export {
  type ApprovalMatch,
  approvalMatchSchema,
  type EvaluationReport,
  type Evidence,
  evaluationReportSchema,
  evidenceSchema,
  type Finding,
  type FindingBasis,
  findingBasisSchema,
  findingSchema,
  type PackageCoordinate,
  type ProviderStatus,
  packageCoordinateSchema,
  providerStatusSchema,
  type Severity,
  severitySchema,
  type Verdict,
  verdictSchema,
} from "./domain.js";
export {
  type HttpErrorKind,
  type JsonHttpClient,
  type JsonRequestClient,
  SafeHttpClient,
  type SafeHttpClientOptions,
  SafeHttpError,
} from "./http/safe-http-client.js";
export {
  type NpmPackageMetadata,
  type NpmProviderResult,
  NpmRegistryProvider,
  type NpmRegistryProviderOptions,
  npmResultForCache,
  parseCachedNpmResult,
} from "./npm/provider.js";
export {
  type NonRegistryKind,
  type NpmNonRegistrySpec,
  type NpmRegistrySpec,
  type NpmSelectorKind,
  NpmSpecError,
  type ParsedNpmSpec,
  parseNpmSpec,
} from "./npm/spec.js";
export {
  cancellationError,
  DeadlineExceededError,
  isOperationCancelled,
  OperationCancelledError,
  type OperationContext,
  throwIfCancelled,
} from "./operation.js";
export {
  classifyOsvRecord,
  type OsvBatchItem,
  type OsvBatchProviderResult,
  type OsvPackageQuery,
  OsvProvider,
  type OsvProviderOptions,
  type OsvProviderResult,
  type OsvRecord,
  type OsvSeverity,
  osvSeveritySchema,
  parseCachedOsvResult,
} from "./osv/provider.js";
export {
  combineVerdicts,
  evaluatePolicy,
  type PolicyEvaluation,
  type PolicyEvaluationError,
  type PolicyEvaluationInput,
} from "./policy/engine.js";
export {
  compareDirectDependencies,
  type DependencyChange,
  type DependencySection,
  type DirectDependency,
  dependencyChangeSchema,
  dependencySectionSchema,
  directDependencies,
  type PackageManifest,
  packageManifestSchema,
} from "./scan/dependencies.js";
export { AGENTHAWK_VERSION } from "./version.js";
